name: Test on Pull Request 

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build hpo
        run: |
          echo Build hpo container image
          ./build.sh -h hpo:test
          docker images | grep hpo     

  test_on_native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sanity test on native
        run: |
          echo Running sanity test on native 
          cd tests
          ./test_hpo.sh -c native --resultsdir=hpo-results --testsuite=hpo_api_tests --testcase=hpo_sanity_test

